# 图像增强
对数据进行扩充，增加数据量和特征的多样性，减少位置、形状对模型训练的影响，使得模型得到充分的训练。

医学图像不同于自然图像,医学图像形状为(H,W),需要增添通道C,以变为(H,W,C),其中C=1.
自然图像为三通道图像(H,W,C),其中C=3.
要想在pytorch框架中进行数据增强操作,需把医学图像转为Image图像,才可进行相对应的操作.
使用pytorch框架,把数据转为tensor时,参考
https://pytorch.org/docs/stable/_modules/torchvision/transforms/transforms.html
https://pytorch.org/docs/stable/_modules/torchvision/transforms/functional.html
if isinstance(pic, np.ndarray):
        # handle numpy array
        img = torch.from_numpy(pic.transpose((2, 0, 1)))#转为Tensor
        # backward compatibility
        if isinstance(img, torch.ByteTensor):
            return img.float().div(255)#除255
        else:
            return img

In [1]:
#导入模块
import pydicom
import numpy as np
import cv2
import torch
#读取医学图像
root ="/home/jascy/桌面/dataprocess/新的DCM格式医学数据/数据增强与扩充/肝细胞癌/zhug_008.dcm"
data = pydicom.read_file(root)
data1 = data.pixel_array
#查看shape
data1.shape

(62, 63)

In [17]:
from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION 
from torchvision import transforms as tfs
pic = np.expand_dims(data1, axis=-1)
if npimg.shape[2] == 1:
    pic = pic[:, :, 0]
# print(pic.shape)
data=(pic, mode='I;16')
np.array(data)

array([[64795, 64839, 64907, ...,    28,    40,    43],
       [64928, 64991, 65066, ...,    42,    44,    31],
       [65075, 65153, 65224, ...,    51,    40,    31],
       ...,
       [   36,    24,    22, ...,    30,    16,     8],
       [   29,    25,    16, ...,    17,     3,     6],
       [   26,    20,    15, ...,     7,     1,    10]], dtype=uint16)

from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
from torchvision import transforms as tfs
#扩充通道C,其中C=1,为灰度"L"
pic = np.expand_dims(data1, axis=-1)
#数据格式转为uint8,范围0-255
npimg=pic.astype(np.uint8)
#转为Tensor
im = tfs.ToTensor()(npimg)

#转为PIL便于增强操作
im= tfs.ToPILImage()(im)
#增强操作
im = tfs.Resize(size=(60,60))(im)

img = tfs.RandomCrop(size=(30,30))(im)

其中PIL数据想要查看shape需要转为numpy,在查看shape
data=np.array(im).shape

In [6]:
#double, float, float16, int64, int32, and uint8.
pic = np.expand_dims(data1, axis=-1)
    
# print(pic.shape)
# print(pic)
# pic = pic/500
# print(pic)
npimg=pic.astype(np.float32)
# print(npimg)
# print(type(npimg))
# print(pic.dtype)
from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
from torchvision import transforms as tfs
im = tfs.ToTensor()(npimg)
print(torch.is_tensor(im))
print(im.shape)
print(im.data)
im= tfs.ToPILImage()(im)
print(np.array(im).shape)
# print(im.format, im.size, im.mode)
im = tfs.Resize(size=(60,60))(im)
# img = tfs.RandomCrop(size=(30,30))(im)
m = tfs.ToTensor()(im)
print(m.shape)
print(m.data)

True
torch.Size([1, 62, 63])
tensor([[[-741., -697., -629.,  ...,   28.,   40.,   43.],
         [-608., -545., -470.,  ...,   42.,   44.,   31.],
         [-461., -383., -312.,  ...,   51.,   40.,   31.],
         ...,
         [  36.,   24.,   22.,  ...,   30.,   16.,    8.],
         [  29.,   25.,   16.,  ...,   17.,    3.,    6.],
         [  26.,   20.,   15.,  ...,    7.,    1.,   10.]]])
(62, 63)
torch.Size([1, 60, 60])
tensor([[[0.8627, 0.6706, 0.4196,  ..., 0.8863, 0.8510, 0.8392],
         [0.3922, 0.2314, 0.7490,  ..., 0.8431, 0.8314, 0.8784],
         [0.7059, 0.5020, 0.3647,  ..., 0.8157, 0.8431, 0.8706],
         ...,
         [0.8706, 0.9059, 0.9176,  ..., 0.8941, 0.9373, 0.9647],
         [0.8902, 0.9098, 0.9412,  ..., 0.9294, 0.9804, 0.9804],
         [0.9020, 0.9294, 0.9412,  ..., 0.9725, 0.9961, 0.9686]]])
